In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('diabetes.csv')
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [5]:
print(f"{df.shape[0]} образцов")
print(f"{df.shape[1]} признаков")
print()
print('1 - есть диабет, 0 - нет диабета')
print(df['Outcome'].value_counts())

768 образцов
9 признаков

1 - есть диабет, 0 - нет диабета
Outcome
0    500
1    268
Name: count, dtype: int64

In [14]:
dataset_lenght : int = df.shape[0]
P_diabetes : float = df['Outcome'].value_counts()[1] / dataset_lenght
#P_diabetes : float = (df['Outcome'] == 1).sum() / dataset_lenght
print(f"вероятность диабета в выборке: {P_diabetes}")

P_older_30 : float = (df['Age'] > 30).sum() / dataset_lenght
print(f"количество людей старше 30 лет в выборке: {P_older_30}")

вероятность диабета в выборке: 0.3489583333333333
количество людей старше 30 лет в выборке: 0.45703125

In [24]:
X = df['BMI'].tolist()

EX = sum(X) / dataset_lenght
print(f"мат. ожидание {EX}")

DX = sum(pow((Xi - EX), 2) for Xi in X) / (dataset_lenght - 1)
print(f"дисперсия {DX}")

P_more_than_35 = sum(1 for Xi in X if Xi > 35) / dataset_lenght
print(f"вероятность, что показатель BMI больше 35 ед.: {P_more_than_35}")

new_df = [out for out, age in zip(df['Outcome'], df['Age']) if age > 23]
P_conditional = sum(new_df) / len(new_df)
print(f"какова вероятность, у человека старше 23 лет есть диабет {P_conditional}")

мат. ожидание 31.992578124999977
дисперсия 62.15998395738257
вероятность, что показатель BMI больше 35 ед.: 0.3177083333333333
какова вероятность, у человека старше 23 лет есть диабет 0.4117647058823529

In [26]:
df_5 = df.sample(n=5, random_state=42)
df_50 = df.sample(n=50, random_state=42)
df_250 = df.sample(n=250, random_state=42)
df_500 = df.sample(n=500, random_state=42)

df_50.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
668,6,98,58,33,190,34.0,0.430,43,0
324,2,112,75,32,0,35.7,0.148,21,0
624,2,108,64,0,0,30.8,0.158,21,0
690,8,107,80,0,0,24.6,0.856,34,0
473,7,136,90,0,0,29.9,0.210,50,0
204,6,103,72,32,190,37.7,0.324,55,0
97,1,71,48,18,76,20.4,0.323,22,0
336,0,117,0,0,0,33.8,0.932,44,0
568,4,154,72,29,126,31.3,0.338,37,0
148,5,147,78,0,0,33.7,0.218,65,0

#### демонстрация закона больших чисел

In [29]:
X_5 = df_5['BMI'].tolist()
X_50 = df_50['BMI'].tolist()
X_250 = df_250['BMI'].tolist()
X_500 = df_500['BMI'].tolist()

EX_5 = sum(X_5) / len(X_5)
EX_50 = sum(X_50) / len(X_50)
EX_250 = sum(X_250) / len(X_250)
EX_500 = sum(X_500) / len(X_500)

print(f"мат. ожидание на выборке размером 5: {EX_5}. доля от мат. ожидания всей выборки: {EX_5/EX}")
print(f"мат. ожидание на выборке размером 50: {EX_50}. доля от мат. ожидания всей выборки: {EX_50/EX}")
print(f"мат. ожидание на выборке размером 250: {EX_250}. доля от мат. ожидания всей выборки: {EX_250/EX}")
print(f"мат. ожидание на выборке размером 500: {EX_500}. доля от мат. ожидания всей выборки: {EX_500/EX}")

мат. ожидание на выборке размером 5: 31.0. доля от мат. ожидания всей выборки: 0.9689747377931901
мат. ожидание на выборке размером 50: 33.07000000000001. доля от мат. ожидания всей выборки: 1.0336772444780904
мат. ожидание на выборке размером 250: 32.064000000000014. доля от мат. ожидания всей выборки: 1.0022324513742213
мат. ожидание на выборке размером 500: 31.969. доля от мат. ожидания всей выборки: 0.9992630126616289